export default {
  //^ 에러
  NULL_VALUE: '필요한 값이 없습니다.',
  OUT_OF_VALUE: '파라미터 값이 잘못되었습니다.',
  NOT_FOUND: '잘못된 경로입니다.',
  NO_IMAGE_TYPE: '이미지 파일이 아닙니다',
  INTERNAL_SERVER_ERROR: '서버 내부 오류',

  //^ 회원가입 및 로그인
  SIGNUP_SUCCESS: '회원 가입 성공',
  SIGNUP_FAIL: '회원 가입 실패',
  SIGNIN_SUCCESS: '로그인 성공',
  SIGNIN_FAIL: '로그인 실패',
  UNAUTHORIZED_SOCIAL: '유효하지 않은 소셜 유저입니다.',
  ALREADY_SIGNED_USER: '이미 가입한 유저입니다.',

  //^ 토큰
  CREATE_TOKEN_SUCCESS: '토큰 재발급 성공',
  EXPIRED_TOKEN: '토큰이 만료되었습니다.',
  EXPIRED_ALL_TOKEN: '모든 토큰이 만료되었습니다.',
  INVALID_ACCESS_TOKEN: '유효하지 않은 액세스 토큰입니다.',
  INVALID_REFRESH_TOKEN: '유효하지 않은 리프레시 토큰입니다.',
  VALID_TOKEN: '유효한 토큰입니다.',
  EMPTY_TOKEN: '토큰 값이 없습니다.',
  NO_USER_TOKEN: '존재하지 않는 유저의 토큰입니다.',
  UPDATE_DEVICE_TOKEN_SUCCESS: '디바이스 토큰 등록 성공',
  UPDATE_DEVICE_TOKEN_FAIL: '디바이스 토큰 등록 실패',

  //^ 유저
  READ_USER_INFO_SUCCESS: '내 정보 조회 성공',
  READ_SPECIFIC_USER_INFO_SUCCESS: '다른 유저 정보 조회 성공',
  READ_USER_BLOCK_SUCCESS: '유저 차단 목록 조회 성공',
  CHECK_USER_NAME_SUCCESS: '유저 닉네임 유효성 체크 성공',
  ALREADY_USER_NAME: '이미 사용중인 닉네임입니다.',
  ALREADY_FOLLOWING_USER: '이미 팔로우한 유저입니다.',
  ALREADY_BLOCK_USER: '이미 차단한 유저입니다.',
  ALREADY_REPORT_USER: '이미 신고한 유저입니다.',
  CAN_NOT_BLOCK_USER: '자신은 차단할 수 없습니다.',
  CAN_NOT_REPORT_USER: '자신은 신고할 수 없습니다.',
  UPDATE_USER_SUCCESS: '유저 닉네임 수정 성공',
  DELETE_USER_SUCCESS: '유저 탈퇴 성공',
  BLOCK_USER_SUCCESS: '유저 차단 성공',
  REPORT_USER_SUCCESS: '유저 신고 성공',
  CANCEL_USER_BLOCK_SUCCESS: '유저 차단 취소 성공',
  BLOCKED_USER: '차단한 유저입니다.',
  NO_BLOCKED_USER: '차단한 유저가 아닙니다.',
  UNAUTHORIZED_USER: '유효하지 않은 유저입니다.',
  NO_USER: '탈퇴했거나 가입하지 않은 유저입니다.',
  NO_USER_ID: '존재하지 않는 유저 Id입니다.',
  NO_USER_UUID: '존재하지 않는 유저의 uuid 값입니다.',
  SEARCH_USER_FAIL: '해당 닉네임을 포함하는 유저가 존재하지 않습니다.',
  UPDATE_USER_DEVICE: '유저 디바이스 등록 성공',
};
